#Compiler PATH
GCC_DIR =
ICC_DIR = /opt/intel/bin

#COMPILER
CC = $(GCC_DIR)gcc
CXX = $(GCC_DIR)g++
AR = $(GCC_DIR)ar

ICC = $(ICC_DIR)/icc
ICPC = $(ICC_DIR)/icpc
#Hibbert's ICC FLAGS
ICCFLAGS = -std=c++0x -vec-report0 -restrict -offload=mandatory #-opt-report-phase=offload 
#Xuechao's ICC FLAGS
ICPCFLAGS = 
MMIC = -mmic


LTE_BENCH_DIR := /home/troore/Projects/xillybench/host/lte
#LTE_BENCH_DIR := /home/$(shell logname)/lte
ifeq "$(LTE_BENCH_DIR)" ""
$(error LTE benchmark project directory is not defined)
endif

LIB_DIR := $(LTE_BENCH_DIR)/lib
SRC_DIR := $(LTE_BENCH_DIR)/src

INC_FLAGS =
INC_FLAGS += -I$(LIB_DIR)

CC_DEBUG_FLAGS = -g
CXX_DEBUG_FLAGS = -g
ICC_DEBUG_FLAGS = -g
ICPC_DEBUG_FLAGS = -g

CC_OPT_FLAGS =
#CXX_OPT_FLAGS = -O3
CXX_OPT_FLAGS = 
ICC_OPT_FLAGS = -O3
ICPC_OPT_FLAGS = -O3

CCFLAGS += $(CC_DEBUG_FLAGS)
CCFLAGS += $(CC_OPT_FLAGS)
CCFLAGS += $(INC_FLAGS)

CXXFLAGS += $(CXX_DEBUG_FLAGS)
CXXFLAGS += $(CXX_OPT_FLAGS)
CXXFLAGS += $(INC_FLAGS)

ICCFLAGS += $(ICC_DEBUG_FLAGS)
ICCFLAGS += $(INC_FLAGS)
ICCFLAGS += $(ICC_OPT_FLAGS)
ICPCFLAGS += $(ICPC_DEBUG_FLAGS)
ICPCFLAGS += $(INC_FLAGS)
ICPCFLAGS += $(ICPC_OPT_FLAGS)

LINKFLAGS =

# OpenCL
AMD_SDK_HOME = /opt/AMDAPP
CUDA_HOME = /usr/local/cuda
OPENCL_SDK_HOME = 
ifeq ($(NV),1)
	OPENCL_SDK_HOME = $(CUDA_HOME)
	INC_FLAGS += -I$(CUDA_HOME)/include
	CXXFLAGS += -DNV
else 
ifeq ($(AMD),1)
OPENCL_SDK_HOME = $(AMD_SDK_HOME)
INC_FLAGS += -I$(AMD_SDK_HOME)/include
endif
endif

# omp
ifeq ($(OMP),1)
	CXXFLAGS += -fopenmp
	LINKFLAGS += -fopenmp
endif
